name: Release

on:
  push:
    branches: [ main, beta ]
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Node Install
        uses: actions/setup-node@v1
        with:
          node-version: [12.x]
      - name: Releasing Packages
        run: yarn release
        env:
          GIT_AUTHOR_EMAIL: ${{ secrets.GIT_AUTHOR_EMAIL }}
          GIT_AUTHOR_NAME: ${{ secrets.GIT_AUTHOR_NAME }}
          GIT_COMMITTER_EMAIL: ${{ secrets.GIT_COMMITTER_EMAIL }}
          GIT_COMMITTER_NAME: ${{ secrets.GIT_COMMITTER_NAME }}
          GITHUB_TOKEN: ${{ secrets.PA_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
